#ifndef WISCOPROS2122_SUBSYSTEMS_LIFT_OPLIFTCONTROLLER_H_
#define WISCOPROS2122_SUBSYSTEMS_LIFT_OPLIFTCONTROLLER_H_

#include "main/main.h"

#endif  // WISCOPROS2122_SUBSYSTEMS_LIFT_AUTONLIFTCONTROLLER_H_